BionicUniversity\StudentBundle\Entity\Cafedra:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fullName:
            type: string
            length: 255
        shortName:
            type: string
            length: 255
    manyToOne:
        faculty:
            targetEntity: Faculty
            inversedBy: cafedras
    oneToMany:
        students:
            targetEntity: Student
            mappedBy: faculty
    lifecycleCallbacks: {  }
