BionicUniversity\StudentBundle\Entity\Faculty:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fullName:
            type: string
            length: 255
        shortName:
            type: string
            length: 255
    manyToOne:
        university:
            targetEntity: University
            inversedBy: faculties
    oneToMany:
        cafedras:
            targetEntity: Cafedra
            mappedBy: faculty
    lifecycleCallbacks: {  }
