bionic_university_user_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BionicUniversityUserBundle:Default:index }
account_register:
    path:     /register
    defaults: { _controller: BionicUniversityUserBundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: BionicUniversityUserBundle:Account:create }