parameters:
#    bionic_university_project.example.class: BionicUniversity\ProjectBundle\Example

services:
#    bionic_university_project.example:
#        class: %bionic_university_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
