BionicUniversity\ProjectBundle\Entity\CompanyService:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        price:
            type: integer
        warranty:
            type: integer
        maintenance:
            type: boolean
        additionally:
            type: string
            length: 255
            nullable: true
    manyToOne:
        service:
            targetEntity: Service
            inersedBy: companies
            joinColumn:
                name: service_id
                referencedColumnName: id
    manyToOne:
        company:
            targetEntity: Company
            inersedBy: services
            joinColumn:
                name: company_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
