BionicUniversity\ProjectBundle\Entity\Service:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
            unique: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: services
            joinColumn:
                name: category_id
                referencedColumnName: id
    oneToMany:
        companies:
            targetEntity: CompanyService
            mappedBy: service

    lifecycleCallbacks: {  }
