bionic_university_user:
        resource: "@BionicUniversityUserBundle/Resources/config/routing.yml"
        prefix:   /
bionic_university_project:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing.yml"
        prefix:   /
BionicUniversityProjectBundle_city:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing/city.yml"
        prefix:   /admin/city
BionicUniversityProjectBundle_address:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing/address.yml"
        prefix:   /address
BionicUniversityProjectBundle_category:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing/category.yml"
        prefix:   /admin/category
BionicUniversityProjectBundle_company:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing/company.yml"
        prefix:   /company
BionicUniversityProjectBundle_companyservice:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing/companyservice.yml"
        prefix:   /companyservice
BionicUniversityProjectBundle_service:
        resource: "@BionicUniversityProjectBundle/Resources/config/routing/service.yml"
        prefix:   /admin/service
BionicUniversityUserBundle_user:
        resource: "@BionicUniversityUserBundle/Resources/config/routing/user.yml"
        prefix:   /user
BionicUniversityUserBundle_role:
        resource: "@BionicUniversityUserBundle/Resources/config/routing/role.yml"
        prefix:   /admin/role
login:
        path:     /login
        defaults: { _controller: BionicUniversityUserBundle:Security:login }
login_check:
        path: /login_check
logout:
        path: /logout